routes/web.php
<?php
Route::match(['get', 'post'], '/login', 'IndexController@login')->name('login');
Route::get('/logout', 'IndexController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'IndexController@index');
    Route::get('/search', 'IndexController@search');
    Route::match(['get', 'post'], '/account', 'IndexController@account');

    Route::get('/data', 'DataController@list');
    Route::match(['get', 'post'], 'data/create', 'DataController@create');
    Route::get('/data/{id}/edit', 'DataController@edit');
    Route::get('/data/{id}/detail', 'DataController@detail');
    Route::get('/data/{id}/del', 'DataController@del');
    Route::get('/data/{id}/contract', 'DataController@downContract');

    Route::get('/staff/division', 'StaffController@divisionList');
    Route::match(['get', 'post'], '/staff/division/create', 'StaffController@divisionCreate');
    Route::match(['get', 'post'], '/staff/division/{id}/edit', 'StaffController@divisionEdit');

    Route::get('/staff', 'StaffController@staffList');
    Route::match(['get', 'post'], '/staff/create', 'StaffController@staffCreate');
    Route::get('/staff/{id}/edit', 'StaffController@staffEdit');
    Route::get('/staff/{id}/detail', 'StaffController@detail');
    Route::get('/staff/{id}/del', 'StaffController@del');

    Route::get('/os/role', 'OsController@roleList');
    Route::match(['get', 'post'], '/os/role/create', 'OsController@create');
    Route::get('/os/role/{id}/edit', 'OsController@edit');

    Route::get('/os/log', 'OsController@loglist');

    Route::match(['get', 'post'], '/sms/send', 'OsController@smsSend');
    Route::get('/sms', 'OsController@smsList');
    Route::get('/sms/sent', 'OsController@smsSentList');
});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    public $table = 'group';
    public $primaryKey = 'gid';
    public $timestamps = false;

    public static $status = [
        0 => '正常',
        1 => '关闭'
    ];

    public function getGstatusAttribute($value)
    {
        return self::$status[(int)$value];
    }

}

app/Operation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Operation extends Model
{
    public $timestamps = false;
    public $table = 'operation_log';

    public function getUidAttribute($value)
    {
        if ($value) {
            return Manage::select('loginname')->find($value)->loginname;
        }

        return '--';
    }
}

app/Http/Controllers/OsController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\Operation;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class OsController extends Controller
{
    public function roleList()
    {
        $groupSelected = Group::select('gid', 'gname')->where('gstatus', 0)->get();
        return view('os.role', [
            'group' => $groupSelected,
        ]);
    }

    public function create(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('os.role_create');
        }

        if ($request->isMethod('post')) {
            $rules = [
                'gname' => 'required|string'
            ];

            $validator = Validator::make($request->all(), $rules);

            if ($validator->fails()) {
                return back()->withErrors($validator);
            }

            if ($request->exists('id')) {
                $groupModel = Group::find($request->get('id'));
            } else {
                $groupModel = new Group();
            }

            $groupModel->gname = $request->get('gname');
            $groupModel->gstatus = 0;

            if (!$groupModel->save()) {
                return back()->withErrors('保存失败');
            }

            return back();
        }
    }

    public function edit($id, Request $request)
    {
        if ($request->isMethod('get')) {
            $groupModel = Group::find($id);

            return view('os.role_edit', [
                'group' => $groupModel
            ]);
        }
    }

    public function loglist(Request $request)
    {
        $operationModel = new Operation();

        if ($request->exists('path') && !empty($request->get('path'))) {
            $operationModel = $operationModel->where('path', $request->get('path'));
        }

        if ($request->exists('start_time') && !empty($request->get('start_time'))) {
            $operationModel = $operationModel->where('create', '>=', $request->get('start_time'));
        }

        if ($request->exists('end_time') && !empty($request->get('end_time'))) {
            $operationModel = $operationModel->where('create', '<=', $request->get('end_time'));
        }

        $operationSelected = $operationModel->paginate(15);

        return view('os.log', [
            'operation' => $operationSelected
        ]);
    }

    public function smsSend(Request $request)
    {
        if ($request->isMethod('get')) {
            $ph = $request->get('ph') ?? '';
            return view('os.sms_send', [
                'ph' => $ph
            ]);
        }

        if ($request->isMethod('post')) {
            $rules = [
                'content' => 'required|string',
                'phone' => 'required|string',
            ];

            $validator = Validator::make($request->all(), $rules);

            if ($validator->fails()) {
                return back()->withErrors($validator);
            }

            $client = new Client([
                'auth' => [config('custom.gateway_user'), config('custom.gateway_password')]
            ]);

            $response = $client->request('POST', config('custom.gateway_task_url'), [
                'json' => [
                    'event' => 'txsms',
                    'userid' => Auth::id(),
                    'num' => $request->get('phone'),
                    'port' => '-1',
                    'encoding' => '8',
                    'smsinfo' => $request->get('content')
                ],
            ]);

            if ($response->getStatusCode() == 200) {
                $resCon = json_decode($response->getBody());

                if ($resCon->result == 'ok') {
                    return back();
                }

                return back()->withErrors($resCon->content);
            }


            return back()->withErrors('短信发送失败');
        }
    }

    public function smsList(Request $request)
    {
        $client = new Client(['auth' => [config('custom.gateway_user'), config('custom.gateway_password')]]);

        $parameter['event'] = 'queryrxsms';

        if ($request->exists('start_time') && !empty($request->get('start_time'))) {
            $parameter['begintime'] = date('YmdHis', strtotime($request->get('start_time')));
        } else {
            $parameter['begintime'] = date('YmdHis', strtotime("-1 week"));
        }

        if ($request->exists('end_time') && !empty($request->get('end_time'))) {
            $parameter['endtime'] = date('YmdHis', strtotime($request->get('end_time')));
        }

        if ($request->exists('phone') && !empty($request->get('phone'))) {
            $parameter['num'] = strtotime($request->get('phone'));
        }

        if ($request->exists('port') && !empty($request->get('port'))) {
            $parameter['port'] = strtotime($request->get('port'));
        }

        $response = $client->request('POST', config('custom.gateway_query_url'), [
            'json' => $parameter
        ]);

        if ($response->getStatusCode() == 200) {
            $resCon = $response->getBody()->getContents();
            $resCon = preg_replace("/\r\n/", '', $resCon);

            $resCon = json_decode($resCon);

            if ($resCon->result == 'ok') {
                $content = explode(';', $resCon->content);

                $content = array_map(function ($item) {
                    return explode(":", $item);
                }, $content);

                unset($content[0]);
                return view('os.sms', ['content' => $content]);
            }
            return back()->withErrors($resCon->content);
        }
        return back()->withErrors('短信获取失败');
    }

    //已经发送的短信
    public function smsSentList(Request $request)
    {
        $client = new Client(['auth' => [config('custom.gateway_user'), config('custom.gateway_password')]]);

        $parameter['event'] = 'querysxsms';

        if ($request->exists('start_time') && !empty($request->get('start_time'))) {
            $parameter['begintime'] = date('YmdHis', strtotime($request->get('start_time')));
        } else {
            $parameter['begintime'] = date('YmdHis', strtotime("-1 week"));
        }

        if ($request->exists('end_time') && !empty($request->get('end_time'))) {
            $parameter['endtime'] = date('YmdHis', strtotime($request->get('end_time')));
        }

        if ($request->exists('phone') && !empty($request->get('phone'))) {
            $parameter['num'] = strtotime($request->get('phone'));
        }

        if ($request->exists('port') && !empty($request->get('port'))) {
            $parameter['port'] = strtotime($request->get('port'));
        }

        $response = $client->request('POST', config('custom.gateway_query_url'), [
            'json' => $parameter
        ]);

        if ($response->getStatusCode() == 200) {
            $resCon = $response->getBody()->getContents();
            $resCon = preg_replace("/\"|}|\|E/", '', $resCon);
            $resCon = explode(';', $resCon);
            if (!empty($resCon)) {
                unset($resCon[0]);

                $resCon = array_map(function ($item) {
                    return explode(":", $item);
                }, $resCon);

                return view('os.sms_sent', ['content' => $resCon]);
            }
            return back()->withErrors($resCon->content);
        }
        return back()->withErrors('短信获取失败');
    }
}

resources/views/os/log.blade.php
@extends('basic')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Data list <small> 数据列表 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Operation log 操作日志</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-12 ibox">
                <div class="ibox-title">
                    <form action="/os/log">
                        <div class="row">
                            <div class="col-sm-3">
                                <input type="text" id="product_name" name="path"
                                       placeholder="Search by path" class="form-control">
                            </div>

                            <div class="col-sm-3">
                                <input type="text" id="start_time" name="start_time" value="" class="form-control"
                                       autocomplete="off" placeholder="开始时间">
                                <script type="text/javascript">
                                    laydate.render({elem: '#start_time'});
                                </script>
                            </div>

                            <div class="col-sm-3">
                                <input type="text" id="end_time" name="end_time" value="{{ old('end_time') }}"
                                       class="form-control"
                                       autocomplete="off" placeholder="结束时间">
                                <script type="text/javascript">
                                    laydate.render({elem: '#end_time'});
                                </script>
                            </div>

                            <div class="col-sm-2">
                                <input type="submit" class="btn btn-info" value="搜索">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <style type="text/css">
                            .table-striped td {
                                max-width: 600px;
                                word-wrap: break-word;
                                word-break: break-all;
                                overflow: hidden;
                            }
                        </style>
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th>操作人</th>
                                <th>路径</th>
                                <th>方式</th>
                                <th>ip</th>
                                <th>信息</th>
                                <th>操作时间</th>

                            @foreach($operation as $item)
                                <tr>
                                    <td>{{ $item->uid }}</td>
                                    <td>{{ $item->path }}</td>
                                    <td>{{ $item->method }}</td>
                                    <td>{{ $item->ip }}</td>
                                    <td>{{ $item->input }}</td>
                                    <td>{{ $item->create }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        {!! $operation->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/os/role.blade.php
@extends('basic')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Data list <small> 数据列表 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Os management 角色管理</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-9 ibox">
                <div class="ibox-title">
                    <div class="col-sm-2">
                        <a href="/os/role/create" class="btn btn-info"> <i class="fa fa-plus"></i> 添加角色</a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive text-center">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th>name (角色名称)</th>
                                <th>status (状态)</th>
                                <th>Operation (操作)</th>
                            </tr>
                            @foreach($group as $item)
                                <tr>
                                    <td> {{ $item->gname }} </td>
                                    <td> {{ $item->gstatus }} </td>
                                    <td>
                                        <a href="/os/role/{{ $item->gid }}/edit" class="btn btn-white btn-sm"><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/os/role_create.blade.php
@extends('basic')

@section('content')
    <style>
        .form-inline .form-group {
            width: 33.3%;
        }

        .form-inline .form-group input {
            width: 100%;
        }
    </style>

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Data addition <small> 数据新增 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <a href="/os/role"><strong>Role list 角色列表</strong></a>
                </li>
                <li class="breadcrumb-item">
                    home 新建角色
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-9 ibox">
                <div class="ibox-title">
                    <h5>Add role <small>添加角色</small></h5>
                </div>
                <div class="ibox-content">
                    <form action="/os/role/create" method="post">
                        {{ csrf_field() }}
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label text-right"> 角色名 * </label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="gname" required>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn" type="submit"> save</button>
                                <a href="/os/log" class="btn btn-white btn"> cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
                <script>
                    var error = "{{ $errors->count() }}";
                    if (error != 0) {
                        alert('{{ $errors->first() }}');
                    }
                </script>
            </div>
        </div>
    </div>
@endsection

resources/views/os/role_edit.blade.php
@extends('basic')

@section('content')
    <style>
        .form-inline .form-group {
            width: 33.3%;
        }

        .form-inline .form-group input {
            width: 100%;
        }
    </style>

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Data addition <small> 数据新增 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <a href="/os/role"><strong>Role list 角色列表</strong></a>
                </li>
                <li class="breadcrumb-item">
                    Edit role 编辑角色
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-9 ibox">
                <div class="ibox-title">
                    <h5>Add role <small>添加角色</small></h5>
                </div>
                <div class="ibox-content">
                    <form action="/os/role/create" method="post">
                        {{ csrf_field() }}
                        <input type="hidden" name="id" value="{{ $group->gid }}">
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label text-right"> 角色名 * </label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="gname" value="{{ $group->gname }}"
                                       required>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn" type="submit"> save</button>
                                <a href="/os/log" class="btn btn-white btn"> cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
                <script>
                    var error = "{{ $errors->count() }}";
                    if (error != 0) {
                        alert('{{ $errors->first() }}');
                    }
                </script>
            </div>
        </div>
    </div>
@endsection

resources/views/os/sms.blade.php
@extends('basic')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Message list <small> 短信列表 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Message list 收到的短信</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-12 ibox">
                <div class="ibox-title">
                    <form action="/sms">
                        <div class="row">
                            <div class="col-sm-2">
                                <input type="text" name="phone" placeholder="来源号码" class="form-control">
                            </div>
                            <div class="col-sm-1">
                                <input type="number" name="port" placeholder="网关端口" class="form-control">
                            </div>
                            <div class="col-sm-2">
                                <input type="text" id="start_time" name="start_time" class="form-control"
                                       autocomplete="off" placeholder="开始时间">
                                <script type="text/javascript">
                                    laydate.render({elem: '#start_time'});
                                </script>
                            </div>
                            <div class="col-sm-2">
                                <input type="text" id="end_time" name="end_time" class="form-control" autocomplete="off"
                                       placeholder="结束时间">
                                <script type="text/javascript">
                                    laydate.render({elem: '#end_time'});
                                </script>
                            </div>
                            <div class="col-sm-1">
                                <input type="submit" class="btn btn-info" value="搜索">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive text-center">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th>time (时间)</th>
                                <th>source (来源号码)</th>
                                <th>content (短信内容)</th>
                                <th>reception (端口卡槽号码)</th>
                            </tr>
                            @if(!empty($content))
                                @foreach($content as $item)
                                    <tr>
                                        <td> {{ date('Y-m-d H:i:s',strtotime($item[0])) }} </td>
                                        <td> {{ $item[2] }} </td>
                                        <td> {{ $item[3] }} </td>
                                        <td> {{ $item[1] }} </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                        <p class="text-info">默认获取最近一周数据</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/os/sms_send.blade.php
@extends('basic')

@section('content')
    <style>
        .form-inline .form-group {
            width: 33.3%;
        }

        .form-inline .form-group input {
            width: 100%;
        }
    </style>

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>send SMS <small> 发送短信 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item">
                    <strong> Send SMS 发送短信 </strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-9 ibox">
                <div class="ibox-title">
                    <h5>send SMS <small>发送短信</small></h5>
                </div>
                <div class="ibox-content">
                    <form action="/sms/send" method="post">
                        {{ csrf_field() }}
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label text-right"> 短信内容 * </label>
                            <div class="col-sm-10">
                                <textarea name="content" class="form-control" rows="10"></textarea>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label text-right"> 发送号码 * </label>
                            <div class="col-sm-10">
                                <textarea name="phone" class="form-control" rows="4" placeholder="多个号码用,隔开">{{ $ph }}</textarea>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        <div class="form-group row">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary btn" type="submit"> send</button>
                                <a href="/os/log" class="btn btn-white btn"> cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
                <script>
                    var error = "{{ $errors->count() }}";
                    if (error != 0) {
                        alert('{{ $errors->first() }}');
                    }
                </script>
            </div>
        </div>
    </div>
@endsection

resources/views/os/sms_sent.blade.php
@extends('basic')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Message list <small> 短信列表 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Message list 发送的短信</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-12 ibox">
                <div class="ibox-title">
                    <form action="/sms">
                        <div class="row">
                            <div class="col-sm-2">
                                <input type="text" name="phone" placeholder="来源号码" class="form-control">
                            </div>
                            <div class="col-sm-1">
                                <input type="number" name="port" placeholder="网关端口" class="form-control">
                            </div>
                            <div class="col-sm-2">
                                <input type="text" id="start_time" name="start_time" class="form-control"
                                       autocomplete="off" placeholder="开始时间">
                                <script type="text/javascript">
                                    laydate.render({elem: '#start_time'});
                                </script>
                            </div>
                            <div class="col-sm-2">
                                <input type="text" id="end_time" name="end_time" class="form-control" autocomplete="off"
                                       placeholder="结束时间">
                                <script type="text/javascript">
                                    laydate.render({elem: '#end_time'});
                                </script>
                            </div>
                            <div class="col-sm-1">
                                <input type="submit" class="btn btn-info" value="搜索">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive text-center">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th>time (时间)</th>
                                <th>source (来源号码)</th>
                                <th>content (短信内容)</th>
                                <th>reception (端口卡槽号码)</th>
                            </tr>
                            @if(!empty($content))
                                @foreach($content as $item)
                                    <tr>
                                        <td> {{ date('Y-m-d H:i:s',strtotime($item[0])) }} </td>
                                        <td> {{ $item[2] }} </td>
                                        <td> {{ $item[4] }} </td>
                                        <td> {{ $item[1] }} </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                        <p class="text-info">默认获取最近一周数据</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection