routes/web.php
<?php
Route::match(['get', 'post'], '/login', 'IndexController@login')->name('login');
Route::get('/logout', 'IndexController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'IndexController@index');
    Route::get('/search', 'IndexController@search');
    Route::match(['get', 'post'], '/account', 'IndexController@account');

    Route::get('/data', 'DataController@list');
    Route::match(['get', 'post'], 'data/create', 'DataController@create');
    Route::get('/data/{id}/edit', 'DataController@edit');
    Route::get('/data/{id}/detail', 'DataController@detail');
    Route::get('/data/{id}/del', 'DataController@del');
    Route::get('/data/{id}/contract', 'DataController@downContract');

    Route::get('/staff/division', 'StaffController@divisionList');
    Route::match(['get', 'post'], '/staff/division/create', 'StaffController@divisionCreate');
    Route::match(['get', 'post'], '/staff/division/{id}/edit', 'StaffController@divisionEdit');

    Route::get('/staff', 'StaffController@staffList');
    Route::match(['get', 'post'], '/staff/create', 'StaffController@staffCreate');
    Route::get('/staff/{id}/edit', 'StaffController@staffEdit');
    Route::get('/staff/{id}/detail', 'StaffController@detail');
    Route::get('/staff/{id}/del', 'StaffController@del');

    Route::get('/os/role', 'OsController@roleList');
    Route::match(['get', 'post'], '/os/role/create', 'OsController@create');
    Route::get('/os/role/{id}/edit', 'OsController@edit');

    Route::get('/os/log', 'OsController@loglist');

    Route::match(['get', 'post'], '/sms/send', 'OsController@smsSend');
    Route::get('/sms', 'OsController@smsList');
    Route::get('/sms/sent', 'OsController@smsSentList');
});

app/Manage.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Manage extends Authenticatable
{
    use Notifiable;

    protected $table = 'manage';

    public $timestamps = false;

    const STATUS_0 = '正常';
    const STATUS_1 = '锁定';
    const STATUS_2 = '关闭';
    public static $status = [
        0 => self::STATUS_0,
        1 => self::STATUS_1,
        2 => self::STATUS_2
    ];

    public static $safe = [
        0 => '启用',
        1 => '关闭'
    ];

    public static $sex = [
        0 => '男',
        1 => '女'
    ];

    public function getGidAttribute($value)
    {
        return Group::select('gname')->find($value)->gname;
    }

    public function getDivisionAttribute($value)
    {
        return Division::select('dname')->find($value)->dname;
    }

    public function getStatusAttribute($value)
    {
        return self::$status[$value];
    }

    public function getSafeAttribute($value)
    {
        return self::$safe[$value];
    }

    public function getSearchingAttribute($value)
    {
        $searchArr = explode(',', $value);
        sort($searchArr);
        $searchArr = array_unique($searchArr);
        $searchArr = array_filter($searchArr);

        $divisonName = Division::select('dname')->whereIn('did', $searchArr)->get()->toArray();
        $divisonName = array_column($divisonName, 'dname');
        $divisonName = implode($divisonName, ',');

        return $divisonName;
    }

    public function getSexAttribute($value)
    {
        return self::$sex[$value];
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    static public $loanStatus = [
        0 => 'YES(已获批)',
        1 => 'NO(未获批)'
    ];


    protected $hidden = [
        'password', 'remember_token',
    ];

    //时间格式化输出
    protected $casts = [
        'email_verified_at' => 'datetime'
    ];

    public $primaryKey = 'uid';

    public $timestamps = false;

    public function getLoanStatusAttribute($value)
    {
        return self::$loanStatus[(int)$value];
    }

    public function getDepartmentAttribute($value)
    {
        $departments = Division::select('did', 'dname')->get()->toArray();

        $departments = array_column($departments, null, 'did');

        return $departments[$value]['dname'] ?? '';
    }

    public function getCreatorAttribute($value)
    {
        $loginname = Manage::select('loginname')->find($value);

        if (empty($loginname)) {
            return '--';

        }

        return $loginname->loginname;
    }
}

app/Http/Controllers/DataController.php
<?php

namespace App\Http\Controllers;

use App\Division;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class DataController extends Controller
{
    public function list(Request $request)
    {
        $userData = User::select('uid', 'IC', 'department', 'Phone', 'LoanStatus', 'LoansCause', 'creator', 'createdate')
            ->orderBy('uid', 'desc');

        if ($request->exists('search') && $request->get('search') != '') {
            $userData = $userData
                ->where('IC', $request->get('search'))
                ->orwhere('Phone', $request->get('search'))
                ->orwhere('Phone1', $request->get('search'))
                ->orwhere('Phone2', $request->get('search'))
                ->orwhere('zip', $request->get('search'))
                ->orwhere('CompanyZip', $request->get('search'))
                ->orwhere('rsphone1', $request->get('search'))
                ->orwhere('rsphone2', $request->get('search'))
                ->orwhere('rsphone3', $request->get('search'))
                ->orwhere('rsphone4', $request->get('search'))
                ->orwhere('rsphone5', $request->get('search'))
                ->orwhere('rsphone6', $request->get('search'));
        }

        $userData = $userData->paginate(20);

        return view('data.data', [
            'user' => $userData,
            'search' => $request->get('search') ?? ''
        ]);
    }

    public function create(Request $request)
    {
        if ($request->isMethod('get')) {
            //depart info
            $divisionData = Division::select('did', 'dname')->where('dstatus', '=', 0)->get();
            //贷款状态
            $loanStatus = User::$loanStatus;

            return view('data.create', [
                'division' => $divisionData,
                'loanStatus' => $loanStatus
            ]);
        }

        if ($request->isMethod('post')) {
            $rules = [
                'ic' => 'required|string',
                'ph1' => 'required|string',
                'division' => 'required'
            ];

            $validator = Validator::make($request->all(), $rules);

            if ($validator->fails()) {
                return back()->withErrors($validator);
            }

            //文件上传
            if (!empty($request->file('agreement'))) {
                $path = $request->file('agreement')->store('agreement');
            }

            if ($request->exists('id')) {
                $userModel = User::find($request->get('id'));
            } else {
                $userModel = new User();
            }

            $userModel->IC = $request->get('ic');
            $userModel->department = $request->get('division');
            $userModel->Phone = $request->get('ph1');
            $userModel->Phone1 = $request->get('ph2');
            $userModel->Phone2 = $request->get('ph3');
            $userModel->LoanStatus = $request->get('loan_cause');
            $userModel->LoansCause = $request->get('loan_reason');
            $userModel->Notes = $request->get('remarks');
            $userModel->tel = $request->get('home_no');
            $userModel->Address = $request->get('home_address');
            $userModel->zip = $request->get('code');
            $userModel->CompanyName = $request->get('campany');
            $userModel->CompanyPhone = $request->get('office_no');
            $userModel->Position = $request->get('position');
            $userModel->Salary = $request->get('salary_data');
            $userModel->WorkingAge = $request->get('loe');
            $userModel->CompanyAddress = $request->get('office_add');
            $userModel->CompanyZip = $request->get('company_code');
            $userModel->createdate = date('Y-m-d H:i:s');
            $userModel->creator = Auth::id();
            $userModel->rsname1 = $request->get('rela_1_name');
            $userModel->rid1 = $request->get('rela_1_relation');
            $userModel->rsphone1 = $request->get('rela_1_ph');
            $userModel->rsname2 = $request->get('rela_2_name');
            $userModel->rid2 = $request->get('rela_2_relation');
            $userModel->rsphone2 = $request->get('rela_2_ph');
            $userModel->rsname3 = $request->get('rela_3_name');
            $userModel->rid3 = $request->get('rela_3_relation');
            $userModel->rsphone3 = $request->get('rela_3_ph');
            $userModel->rsname4 = $request->get('rela_4_name');
            $userModel->rid4 = $request->get('rela_4_relation');
            $userModel->rsphone4 = $request->get('rela_4_ph');
            $userModel->rsname5 = $request->get('rela_5_name');
            $userModel->rid5 = $request->get('rela_5_relation');
            $userModel->rsphone5 = $request->get('rela_5_ph');
            $userModel->rsname6 = $request->get('rela_6_name');
            $userModel->rid6 = $request->get('rela_6_relation');
            $userModel->rsphone6 = $request->get('rela_6_ph');

            if (!empty($request->file('agreement'))) {
                $userModel->agreement = $path;
            }

            if ($request->exists('id')) {
                $userModel->updatedate = date('Y-m-d H:i:s');
            }

            if ($userModel->save()) {
                return back();
            }

            return back()->with('errors', 'Have an error');
        }
    }

    public function edit($id, Request $request)
    {
        if ($request->isMethod('get')) {
            $user = User::find($id);
            $loanStatus = User::$loanStatus;

            $divisonSelected = Division::select('did', 'dname')->get();

            return view('data.edit', [
                'user' => $user,
                'loanStatus' => $loanStatus,
                'division' => $divisonSelected
            ]);
        }
    }

    public function detail($id)
    {
        $user = User::find($id);
        $loanStatus = User::$loanStatus;

        return view('data.detail', [
            'user' => $user,
            'loanStatus' => $loanStatus
        ]);
    }

    //下载合同
    public function downContract($id)
    {
        $agreement = User::select('IC', 'agreement')->find($id);
        if ($agreement->agreement) {
            $file = storage_path() . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . $agreement->agreement;
            $file_ext = explode('.', $file);
            $name = $agreement->IC . '_contract_.' . $file_ext[count($file_ext) - 1];

            return response()->download($file, $name);
        }

        return back();
    }

    //删除
    public function del($id)
    {
        if (User::destroy($id)) {
            return 200;
        }
    }
}

resources/views/data/data.blade.php
@extends('basic')

@section('content')
    <div id="modal-form" class="modal" style="background: rgba(0,0,0,0.4)">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-6 b-r">
                            <h3>You want to delete it? </h3>
                            <br>
                            <div>
                                <button class="btn btn-block btn-primary" type="submit" id="remove_del">
                                    <strong>No</strong></button>
                                <button id="action_del" class="btn btn-block" type="submit">yes
                                </button>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <p class="text-center">
                                <i class="fa fa-trash-o big-icon"></i>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Data list <small> 数据列表 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Data list 数据列表</strong>
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-12 ibox">
                <div class="ibox-title">
                    <form action="/data" type="get">
                        <div class="row">
                            <div class="col-sm-4">
                                <input type="text" name="search" placeholder="Search by IC or Phone or company name or Postal Code"
                                       value="{{ $search }}" class="form-control">
                            </div>
                            <div class="col-sm-2">
                                <input type="submit" class="btn btn-info" value="搜索">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive text-center">
                        <table class="table table-striped">
                            <tbody>
                            <tr>
                                <th>ID(编号)</th>
                                <th>COUNTER(所属分部)</th>
                                <th>IC (身份证)</th>
                                <th>HP (手机)</th>
                                <th>APPROVED? (是否批款)</th>
                                <th>REASON IF NO (未批原因)</th>
                                <th>CREATOR (创建者)</th>
                                <th>Entry Time (录入时间)</th>
                                <th>Operation (操作)</th>
                            </tr>

                            @foreach($user as $item)
                                <tr>
                                    <td>{{ $item->uid }}</td>
                                    <td>{{ $item->department }}</td>
                                    <td>
                                        <span
                                            class="{{ $item->IC==$search?'font-bold text-success':'' }}">{{ $item->IC }}</span>
                                    </td>
                                    <td>
                                        <span class="{{ $item->Phone==$search?'font-bold text-success':'' }}">
                                            {{ Auth::user()->gid == '员工' && !empty(trim($item->Phone))?substr_replace($item->Phone,'**',3,2):$item->Phone }}
                                        </span>
                                    </td>
                                    <td>{{ $item->LoanStatus }}</td>
                                    <td width="40%">{{ $item->LoansCause }}</td>
                                    <td>{{ $item->creator }}</td>
                                    <td>{{ $item->createdate }}</td>
                                    <td>
                                        <a href="/data/{{ $item->uid }}/detail" class="btn btn-white btn-sm">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                        @if(Auth::user()->gid == '员工' && $item->createdate >= date('Y-m-d'))
                                            <a href="/data/{{ $item->uid }}/edit" class="btn btn-white btn-sm">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        @endif
                                        @if(Auth::user()->gid != '员工')
                                            <a href="/data/{{ $item->uid }}/edit" class="btn btn-white btn-sm">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        @endif

                                        {{-- @if(Auth::user()->gid == '管理员')
                                             <button class="btn btn-white btn-sm" onclick="del_item({{ $item->uid }})">
                                                 <i class="fa fa-trash-o"></i>
                                             </button>
                                         @endif--}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                    {!! $user->links() !!}
                </div>
            </div>
        </div>
    </div>
    <script>
        function del_item(id) {
            $("#modal-form").fadeIn();
            $("#action_del").click(function () {
                $.get("/data/" + id + "/del", function (data) {
                    if (data == 200) {
                        location.reload();
                    }
                });
            });
            $("#remove_del").click(function () {
                $("#modal-form").fadeOut();
            });
        }
    </script>
@endsection

resources/views/data/detail.blade.php
@extends('basic')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Data list <small> 数据列表 </small></h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/">home 首页</a>
                </li>
                <li class="breadcrumb-item active">
                    <a href="/data"><strong>Data list 数据列表</strong></a>
                </li>
                <li class="breadcrumb-item active">
                    See details 查看详情
                </li>
            </ol>
        </div>
    </div>

    <div class="page-content">
        <div class="row wrapper wrapper-content animated fadeInRight">
            <div class="col-md-12 ibox">
                <div class="ibox-title">
                    ID : {{ $user->uid }}
                    <div class="ibox-tools">
                        <a href="/data/{{ $user->uid }}/contract"> <span class="label label-primary">Download contract scan（下载合同扫描件） </span></a>
                    </div>
                </div>
                <div class="ibox-content">
                    <table class="table table-hover no-margins">
                        <thead>
                        <tr>
                            <th width="15%">属性名</th>
                            <th>属性值</th>
                            <th width="15%">属性名</th>
                            <th>属性值</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td> IC</td>
                            <td>{{ $user->IC }}</td>
                            <td> NAME1(名字)</td>
                            <td>{{ $user->rsname1 }}</td>
                        </tr>
                        <tr>
                            <td> COUNTER(分部)</td>
                            <td>{{ $user->department }}</td>
                            <td> RELATIONSHIP1(关系)</td>
                            <td>{{ $user->rid1 }}</td>
                        </tr>
                        <tr>
                            <td> Phone(手机)</td>
                            <td>
                                {{ $user->Phone }}
                                @if($user->Phone != ' ')
                                    <a href="/sms/send?ph={{ $user->Phone }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                            <td> HP1</td>
                            <td>{{ $user->rsphone1 }}
                                @if($user->rsphone1)
                                    <a href="/sms/send?ph={{ $user->rsphone1 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td> Phone1</td>
                            <td>{{ $user->Phone1 }}
                                @if($user->Phone1)
                                    <a href="/sms/send?ph={{ $user->Phone1 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                            <td> NAME2(名字)</td>
                            <td>{{ $user->rsname2 }}</td>
                        </tr>
                        <tr>
                            <td> Phone2</td>
                            <td>{{ $user->Phone2 }}
                                @if($user->Phone2)
                                    <a href="/sms/send?ph={{ $user->Phone2 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                            <td> RELATIONSHIP2(关系)</td>
                            <td>{{ $user->rid2 }}</td>
                        </tr>
                        <tr>
                            <td> APPROVED ?(是否批款?)</td>
                            <td>{{ $user->LoanStatus }}</td>
                            <td> HP2</td>
                            <td>{{ $user->rsphone2 }}
                                @if($user->rsphone2 )
                                    <a href="/sms/send?ph={{ $user->rsphone2 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td> REASON IF NO(原因)</td>
                            <td>{{ $user->LoansCause }}</td>
                            <td> NAME3(名字)</td>
                            <td>{{ $user->rsname3 }}</td>
                        </tr>
                        <tr>
                            <td> REMARKS(备注)</td>
                            <td>{{ $user->Notes }}</td>
                            <td> RELATIONSHIP3(关系)</td>
                            <td>{{ $user->rid3 }}</td>
                        </tr>
                        <tr>
                            <td> ADDRESS(住址)</td>
                            <td>{{ $user->Address }}</td>
                            <td> HP3</td>
                            <td>{{ $user->rsphone3 }}
                                @if($user->rsphone3)
                                    <a href="/sms/send?ph={{ $user->rsphone3 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td> HOME NO(住家电话)</td>
                            <td>{{ $user->tel }}</td>
                            <td> NAME4(名字)</td>
                            <td>{{ $user->rsname4 }}</td>
                        </tr>
                        <tr>
                            <td> POSTAL CODE(住址邮编)</td>
                            <td>{{ $user->zip }}</td>
                            <td> RELATIONSHIP4(关系)</td>
                            <td>{{ $user->rid4 }}</td>
                        </tr>
                        <tr>
                            <td> CAMPANY NAME(公司名称)</td>
                            <td>{{ $user->CompanyName }}</td>
                            <td> HP4</td>
                            <td>{{ $user->rsphone4 }}
                                @if($user->rsphone4)
                                    <a href="/sms/send?ph={{ $user->rsphone4 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td> POSITION(工作职位)</td>
                            <td>{{ $user->Position }}</td>
                            <td> NAME5(名字)</td>
                            <td>{{ $user->rsname5 }}</td>
                        </tr>
                        <tr>
                            <td> LOE(工龄)</td>
                            <td>{{ $user->WorkingAge }}</td>
                            <td> RELATIONSHIP5(关系)</td>
                            <td>{{ $user->rid5 }}</td>
                        </tr>
                        <tr>
                            <td> Date of Salary(发薪日)</td>
                            <td>{{ $user->Salary }}</td>
                            <td> HP5</td>
                            <td>{{ $user->rsphone5 }}
                                @if($user->rsphone5)
                                    <a href="/sms/send?ph={{ $user->rsphone5 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td> OFFICE NO(公司电话)</td>
                            <td>{{ $user->CompanyPhone }}</td>
                            <td> NAME6(名字)</td>
                            <td>{{ $user->rsname6 }}</td>
                        </tr>
                        <tr>
                            <td> ADDRESS(公司地址)</td>
                            <td>{{ $user->CompanyAddress }}</td>
                            <td> RELATIONSHIP6(关系)</td>
                            <td>{{ $user->rid6 }}</td>
                        </tr>
                        <tr>
                            <td> POSTAL CODE(公司邮编)</td>
                            <td>{{ $user->CompanyZip }}</td>
                            <td> HP6</td>
                            <td>{{ $user->rsphone6 }}
                                @if($user->rsphone6)
                                    <a href="/sms/send?ph={{ $user->rsphone6 }}"><i
                                            class="fa fa-envelope text-info"></i></a>
                                @endif
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection